export { default as Account } from '@/components/Account';
export { default as Button } from '@/components/Button';
export { default as Cart } from '@/components/Cart';
export { default as Filters } from '@/components/Filters';
export { default as Footer } from '@/components/Footer';
export { default as LoginForm } from '@/components/LoginForm';
export { default as Navigation } from '@/components/Navigation';
export { default as Payment } from '@/components/Payment';
export { default as Rating } from '@/components/Rating';
export { default as RegisterForm } from '@/components/RegisterForm';
export { default as Searchbar } from '@/components/Searchbar';
export { default as SingleMeal } from '@/components/SingleMeal';
export { default as Slider } from '@/components/Slider';
export { default as StripeCheckout } from '@/components/StripeCheckout';
export { default as ProtectedRoute } from "@/components/ProtectedRoute"
export { default as Loading } from "@/components/Loading"